packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.2.1
  '@commitlint/cli': ^19.7.1
  '@commitlint/config-conventional': ^19.7.1
  '@date-fns/tz': ^1.2.0
  '@dicebear/collection': ^9.2.2
  '@dicebear/core': ^9.2.2
  '@iconify-json/circle-flags': ^1.2.6
  '@iconify-json/lucide': ^1.2.26
  '@iconify-json/pixelarticons': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.24
  '@neoconfetti/vue': ^2.2.1
  '@nuxt/devtools': ^2.1.0
  '@nuxt/image': ^1.9.0
  '@nuxt/ui': 3.0.0-alpha.13
  '@nuxtjs/i18n': ^9.2.0
  '@paralleldrive/cuid2': ^2.2.2
  '@semantic-release/exec': ^7.0.3
  '@semantic-release/git': ^10.0.1
  '@types/bcrypt': ^5.0.2
  '@types/node': ^22.13.4
  '@types/nodemailer': ^6.4.17
  '@types/pg': ^8.11.11
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/browser': ^3.0.5
  '@vitest/coverage-v8': ^3.0.5
  '@vue-email/components': ^0.0.21
  '@vue-email/render': ^0.0.9
  '@vueuse/core': ^12.7.0
  '@vueuse/nuxt': ^12.7.0
  aws4fetch: ^1.0.20
  bcrypt: ^5.1.1
  dotenv: ^16.4.7
  dotenv-cli: ^8.0.0
  drizzle-cuid2: ^2.0.0
  drizzle-kit: ^0.30.4
  drizzle-orm: ^0.39.3
  eslint: ^9.20.1
  husky: ^9.1.7
  libphonenumber-js: ^1.11.20
  lint-staged: ^15.4.3
  nodemailer: ^6.10.0
  nuxt: ^3.15.4
  nuxt-auth-utils: ^0.5.15
  nuxt-zod-i18n: ^1.11.5
  pg: ^8.13.3
  playwright: ^1.50.1
  semantic-release: ^24.2.3
  semantic-release-monorepo: ^8.0.2
  sharp: ^0.33.5
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vite: ^6.1.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
  vitest-browser-vue: ^0.1.0
  zod: ^3.24.2
