apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-pv-claim
  namespace: next-orders
spec:
  storageClassName: csi-s3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi