services:
  db:
    image: postgres:17-alpine
    container_name: food-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - next_orders_pg_data:/var/lib/postgresql/data

  # app:
  #   image: food/app:local
  #   container_name: food-app
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
  #   ports:
  #     - '3500:3000'

  # landing:
  #   image: food/landing:local
  #   container_name: food-landing
  #   restart: unless-stopped
  #   ports:
  #     - '3501:3000'

volumes:
  next_orders_pg_data:
