---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: next-orders
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: website
    spec:
      securityContext:
        runAsUser: 1001
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: website
          image: ghcr.io/next-orders/website:nightly
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_SESSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: NUXT_SESSION_PASSWORD
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          livenessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 20
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
